<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="2" hostname="DESKTOP-5OULTSJ" failures="1" tests="1" name="Test Basics 2(failed)" time="0.002" errors="0" timestamp="13 Jun 2022 02:43:22 GMT">
  <testcase classname="Factory.Test2" name="testFail" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at Factory.Test2.testFail(Test2.java:24)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:831)
... Removed 20 stack frames]]>
    </failure>
  </testcase> <!-- testFail -->
  <testcase classname="Factory.Test2" name="test22mehtod" time="0.0">
    <ignored/>
  </testcase> <!-- test22mehtod -->
  <testcase classname="Factory.Test2" name="test2method" time="0.0">
    <ignored/>
  </testcase> <!-- test2method -->
</testsuite> <!-- Test Basics 2(failed) -->
